//AUTH
export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const USER_LOGEDED = "USER_LOGEDED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const EDITAR_OPERADOR = "EDITAR_OPERADOR";
export const MOSTRAR_OPERADOR = "MOSTRAR_OPERADOR";

// CAMPAÑAS
export const AT = "AT";
export const BLANQUEO = "BLANQUEO";
export const REC = "REC";
export const REIN = "REIN";
export const BUSCAR_CASO = "BUSCAR_CASO";
export const CREAR_CAMP_AT = "CREAR_CAMP_AT";
export const ESTADO_CAMP = "ESTADO_CAMP";
export const CAMPANA_OPERADOR = "CAMPANA_OPERADOR";
export const CAMPANA_OPERADOR_TRAB = "CAMPANA_OPERADOR_TRAB";
export const CAMPANA_OPERADOR_NOTI = "CAMPANA_OPERADOR_NOTI";
export const GESTION_CASO = "GESTION_CASO";
export const UPDATE_ACCION = "UPDATE_ACCION";
export const CERRAR_CASO = "CERRAR_CASO";
export const GET_GESTION_CASO = "GET_GESTION_CASO";
export const GET_RECUPERACION = "GET_RECUPERACION";
export const GET_DEUDA = "GET_DEUDA";

//ESTADISTICAS
export const LLAMADAS_INCONCLUSAS = "LLAMADAS_INCONCLUSAS";
export const COMPROMISO_PAGO = "COMPROMISO_PAGO";
export const NO_PAGA = "NO_PAGA";
export const CUOTA_DIA = "CUOTA_DIA";
export const NOTIFICACION = "NOTIFICACION";
export const CARTERA_ROJA = "CARTERA_ROJA";
export const SOCIO_FALLECIDO = "SOCIO_FALLECIDO";
export const CASOS_ABIERTOS = "CASOS_ABIERTOS";
export const CASOS_CERRADOS = "CASOS_CERRADOS";
export const CASOS_SIN_ACCION = "CASOS_SIN_ACCION";
export const CASOS_CON_ACCION = "CASOS_CON_ACCION";
