//AUTH
export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const USER_LOGEDED = "USER_LOGEDED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const EDITAR_OPERADOR = "EDITAR_OPERADOR";
export const MOSTRAR_OPERADOR = "MOSTRAR_OPERADOR";

// CAMPAÑAS
export const AT = "AT";
export const BLANQUEO = "BLANQUEO";
export const REC = "REC";
export const REIN = "REIN";
export const POLICIA = "POLICIA";
export const BUSCAR_CASO = "BUSCAR_CASO";
export const CREAR_CAMP_AT = "CREAR_CAMP_AT";
export const ESTADO_CAMP = "ESTADO_CAMP";
export const CAMPANA_OPERADOR = "CAMPANA_OPERADOR";
export const CAMPANA_OPERADOR_TRAB = "CAMPANA_OPERADOR_TRAB";
export const CAMPANA_OPERADOR_NOTI = "CAMPANA_OPERADOR_NOTI";
export const CAMPANA_OPERADOR_HIST = "CAMPANA_OPERADOR_HIST";
export const GESTION_CASO = "GESTION_CASO";
export const UPDATE_ACCION = "UPDATE_ACCION";
export const CERRAR_CASO = "CERRAR_CASO";
export const GET_GESTION_CASO = "GET_GESTION_CASO";
export const GET_RECUPERACION = "GET_RECUPERACION";
export const GET_DEUDA = "GET_DEUDA";

//ESTADISTICAS
export const LLAMADAS_INCONCLUSAS = "LLAMADAS_INCONCLUSAS";
export const COMPROMISO_PAGO = "COMPROMISO_PAGO";
export const NO_PAGA = "NO_PAGA";
export const CUOTA_DIA = "CUOTA_DIA";
export const NOTIFICACION = "NOTIFICACION";
export const CARTERA_ROJA = "CARTERA_ROJA";
export const SOCIO_FALLECIDO = "SOCIO_FALLECIDO";
export const CASOS_ABIERTOS = "CASOS_ABIERTOS";
export const CASOS_CERRADOS = "CASOS_CERRADOS";
export const CASOS_SIN_ACCION = "CASOS_SIN_ACCION";
export const CASOS_CON_ACCION = "CASOS_CON_ACCION";

//NOTICIAS
export const NUEVA_NOTICIA = "NUEVA_NOTICIA";
export const MOSTRAR_NOTICIA = "MOSTRAR_NOTICIA";

//MORA
export const MCOBRADORES = "MCOBRADORES";
export const MOFICINA = "MOFICINA";
export const MTARJETA = "MTARJETA";
export const MBANCONV = "MBANCONV";

//EFECTIVIDAD
export const ECOBRADORES = "ECOBRADORES";
export const EOFICINA = "EOFICINA";
export const ECOBRADORES_COBRADO = "ECOBRADORES_COBRADO";
export const EOFICINA_COBRADO = "EOFICINA_COBRADO";
export const ETARJETA_P = "ETARJETA_P";
export const ETARJETA_L = "ETARJETA_L";
export const ETARJETA_W = "ETARJETA_W";
export const ETARJETA_R = "ETARJETA_R";
export const EPOLICIA = "EPOLICIA";
export const ECONVENIOS = "ECONVENIOS";
export const EBANCO = "EBANCO";
