//AUTH
export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const USER_LOGEDED = "USER_LOGEDED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const EDITAR_OPERADOR = "EDITAR_OPERADOR";
export const MOSTRAR_OPERADOR = "MOSTRAR_OPERADOR";

// CAMPAÑAS
export const AT = "AT";
export const BLANQUEO = "BLANQUEO";
export const REC = "REC";
export const REIN = "REIN";
export const POLICIA = "POLICIA";
export const AUX = "AUX";
export const BUSCAR_CASO = "BUSCAR_CASO";
export const BUSCAR_GESTION_CASO = "BUSCAR_GESTION_CASO";
export const CREAR_CAMP_AT = "CREAR_CAMP_AT";
export const ESTADO_CAMP = "ESTADO_CAMP";
export const CAMPANA_OPERADOR = "CAMPANA_OPERADOR";
export const CAMPANA_OPERADOR_TRAB = "CAMPANA_OPERADOR_TRAB";
export const CAMPANA_OPERADOR_NOTI = "CAMPANA_OPERADOR_NOTI";
export const CAMPANA_OPERADOR_HIST = "CAMPANA_OPERADOR_HIST";
export const GESTION_CASO = "GESTION_CASO";
export const UPDATE_ACCION = "UPDATE_ACCION";
export const CERRAR_CASO = "CERRAR_CASO";
export const CERRAR_GESTION = "CERRAR_GESTION";
export const GET_GESTION_CASO = "GET_GESTION_CASO";
export const GET_RECUPERACION = "GET_RECUPERACION";
export const GET_DEUDA = "GET_DEUDA";
export const BUSCAR_CAMPANAS = "BUSCAR_CAMPANAS";
export const BUSCAR_CAMPANAS_REC = "BUSCAR_CAMPANAS_REC";
export const BUSCAR_CAMPANAS_REIN = "BUSCAR_CAMPANAS_REIN";
export const BUSCAR_CAMPANAS_BLAN = "BUSCAR_CAMPANAS_BLAN";
export const BUSCAR_CAMPANAS_AUX = "BUSCAR_CAMPANAS_AUX";
export const CERRAR_CAMPAÑAS = "CERRAR_CAMPAÑAS";

//ESTADISTICAS
export const LLAMADAS_INCONCLUSAS = "LLAMADAS_INCONCLUSAS";
export const COMPROMISO_PAGO = "COMPROMISO_PAGO";
export const NO_PAGA = "NO_PAGA";
export const CUOTA_DIA = "CUOTA_DIA";
export const NOTIFICACION = "NOTIFICACION";
export const CARTERA_ROJA = "CARTERA_ROJA";
export const SOCIO_FALLECIDO = "SOCIO_FALLECIDO";
export const CASOS_ABIERTOS = "CASOS_ABIERTOS";
export const CASOS_CERRADOS = "CASOS_CERRADOS";
export const CASOS_SIN_ACCION = "CASOS_SIN_ACCION";
export const CASOS_CON_ACCION = "CASOS_CON_ACCION";

//NOTICIAS
export const NUEVA_NOTICIA = "NUEVA_NOTICIA";
export const MOSTRAR_NOTICIA = "MOSTRAR_NOTICIA";

//MORA
export const MCOBRADORES = "MCOBRADORES";
export const MOFICINA = "MOFICINA";
export const MTARJETA = "MTARJETA";
export const MBANCONV = "MBANCONV";

//EFECTIVIDAD
export const ECOBRADORES = "ECOBRADORES";
export const EOFICINA = "EOFICINA";
export const ECOBRADORES_COBRADO = "ECOBRADORES_COBRADO";
export const EOFICINA_COBRADO = "EOFICINA_COBRADO";
export const ETARJETA_P = "ETARJETA_P";
export const ETARJETA_L = "ETARJETA_L";
export const ETARJETA_W = "ETARJETA_W";
export const ETARJETA_R = "ETARJETA_R";
export const EPOLICIA = "EPOLICIA";
export const ECONVENIOS = "ECONVENIOS";
export const EBANCO = "EBANCO";
export const RESPALCOB = "RESPALCOB";
export const RESPERCOB = "RESPERCOB";
export const RESSPCOB = "RESSPCOB";
export const RESSSJCOB = "RESSSJCOB";
export const RESPALCOBM = "RESPALCOBM";
export const RESPERCOBM = "RESPERCOBM";
export const RESSPCOBM = "RESSPCOBM";
export const RESSSJCOBM = "RESSSJCOBM";
export const RESPALOFI = "RESPALOFI";
export const RESPEROFI = "RESPEROFI";
export const RESSPOFI = "RESSPOFI";
export const RESSSJOFI = "RESSSJOFI";
export const RESPALOFIM = "RESPALOFIM";
export const RESPEROFIM = "RESPEROFIM";
export const RESSPOFIM = "RESSPOFIM";
export const RESSSJOFIM = "RESSSJOFIM";
export const RESPALTAR = "RESPALTAR";
export const RESPERTAR = "RESPERTAR";
export const RESSPTAR = "RESSPTAR";
export const RESSSJTAR = "RESSSJTAR";
export const RESPALTARM = "RESPALTARM";
export const RESPERTARM = "RESPERTARM";
export const RESSPTARM = "RESSPTARM";
export const RESSSJTARM = "RESSSJTARM";
export const RESPALBAN = "RESPALBAN";
export const RESPERBAN = "RESPERBAN";
export const RESSPBAN = "RESSPBAN";
export const RESSSJBAN = "RESSSJBAN";
export const RESPALPOL = "RESPALPOL";
export const RESPERPOL = "RESPERPOL";
export const RESSPPOL = "RESSPPOL";
export const RESSSJPOL = "RESSSJPOL";
export const RESPALCONV = "RESPALCONV";
export const RESPERCONV = "RESPERCONV";
export const RESSPCONV = "RESSPCONV";
export const RESSSJCONV = "RESSSJCONV";

// SEPELIO
export const NUEVA_CAJA = "NUEVA_CAJA";
export const NUEVO_INGRESO = "NUEVO_INGRESO";
export const LISTADO_CAJAS = "LISTADO_CAJAS";
export const CAJA = "CAJA";
export const GASTO = "GASTO";
export const NUEVO_GASTO = "NUEVO_GASTO";
export const UPDATE_GASTO = "UPDATE_GASTO";
export const UPDATE_TOTALES = "UPDATE_TOTALES";
export const UPDATE_CIERRE_CAJA = "UPDATE_CIERRE_CAJA";
export const LISTADO_GASTOS = "LISTADO_GASTOS";
export const LISTADO_INGRESOS = "LISTADO_INGRESOS";
export const ELIMINAR_GASTO = "ELIMINAR_GASTO";
export const ELIMINAR_CAJA = "ELIMINAR_CAJA";
export const ELIMINAR_INGRESO = "ELIMINAR_INGRESO";

// VENTAS
export const CONSULTA_VENTAS = "CONSULTA_VENTAS";
export const CONSULTA_VENTASM = "CONSULTA_VENTASM";

// PRESTAMOS
export const CONSULTAR_FICHA = "CONSULTAR_FICHA";
export const ALTA_PRESTAMO = "ALTA_PRESTAMO";
export const LISTADO_PRESTAMOS = "LISTADO_PRESTAMOS";
export const PRESTAMOR_POR_OP = "PRESTAMOR_POR_OP";
export const PRESTAMOR_POR_ESTADO = "PRESTAMOR_POR_ESTADO";
export const APROBAR_PRESTAMOS = "APROBAR_PRESTAMOS";
